package zy.epip.model.platform;

import java.io.Serializable;
import java.util.Date;

public class TbTeacher implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.img_path
     *
     * @mbg.generated
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.yjfx
     *
     * @mbg.generated
     */
    private String yjfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.yjcg
     *
     * @mbg.generated
     */
    private String yjcg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.jiangxiren_type
     *
     * @mbg.generated
     */
    private String jiangxirenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.ziyuan_type
     *
     * @mbg.generated
     */
    private String ziyuanType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.zt
     *
     * @mbg.generated
     */
    private Integer zt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_teacher.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_teacher
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.id
     *
     * @return the value of tb_teacher.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.id
     *
     * @param id the value for tb_teacher.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.name
     *
     * @return the value of tb_teacher.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.name
     *
     * @param name the value for tb_teacher.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.sex
     *
     * @return the value of tb_teacher.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.sex
     *
     * @param sex the value for tb_teacher.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.duty
     *
     * @return the value of tb_teacher.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.duty
     *
     * @param duty the value for tb_teacher.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.img_path
     *
     * @return the value of tb_teacher.img_path
     *
     * @mbg.generated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.img_path
     *
     * @param imgPath the value for tb_teacher.img_path
     *
     * @mbg.generated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.yjfx
     *
     * @return the value of tb_teacher.yjfx
     *
     * @mbg.generated
     */
    public String getYjfx() {
        return yjfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.yjfx
     *
     * @param yjfx the value for tb_teacher.yjfx
     *
     * @mbg.generated
     */
    public void setYjfx(String yjfx) {
        this.yjfx = yjfx == null ? null : yjfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.yjcg
     *
     * @return the value of tb_teacher.yjcg
     *
     * @mbg.generated
     */
    public String getYjcg() {
        return yjcg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.yjcg
     *
     * @param yjcg the value for tb_teacher.yjcg
     *
     * @mbg.generated
     */
    public void setYjcg(String yjcg) {
        this.yjcg = yjcg == null ? null : yjcg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.jiangxiren_type
     *
     * @return the value of tb_teacher.jiangxiren_type
     *
     * @mbg.generated
     */
    public String getJiangxirenType() {
        return jiangxirenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.jiangxiren_type
     *
     * @param jiangxirenType the value for tb_teacher.jiangxiren_type
     *
     * @mbg.generated
     */
    public void setJiangxirenType(String jiangxirenType) {
        this.jiangxirenType = jiangxirenType == null ? null : jiangxirenType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.ziyuan_type
     *
     * @return the value of tb_teacher.ziyuan_type
     *
     * @mbg.generated
     */
    public String getZiyuanType() {
        return ziyuanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.ziyuan_type
     *
     * @param ziyuanType the value for tb_teacher.ziyuan_type
     *
     * @mbg.generated
     */
    public void setZiyuanType(String ziyuanType) {
        this.ziyuanType = ziyuanType == null ? null : ziyuanType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.zt
     *
     * @return the value of tb_teacher.zt
     *
     * @mbg.generated
     */
    public Integer getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.zt
     *
     * @param zt the value for tb_teacher.zt
     *
     * @mbg.generated
     */
    public void setZt(Integer zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.create_time
     *
     * @return the value of tb_teacher.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.create_time
     *
     * @param createTime the value for tb_teacher.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.create_user
     *
     * @return the value of tb_teacher.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.create_user
     *
     * @param createUser the value for tb_teacher.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.update_time
     *
     * @return the value of tb_teacher.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.update_time
     *
     * @param updateTime the value for tb_teacher.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_teacher.update_user
     *
     * @return the value of tb_teacher.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_teacher.update_user
     *
     * @param updateUser the value for tb_teacher.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", duty=").append(duty);
        sb.append(", imgPath=").append(imgPath);
        sb.append(", yjfx=").append(yjfx);
        sb.append(", yjcg=").append(yjcg);
        sb.append(", jiangxirenType=").append(jiangxirenType);
        sb.append(", ziyuanType=").append(ziyuanType);
        sb.append(", zt=").append(zt);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}