package cn.bj.zy.sbframework.mapper.platform;

import cn.bj.zy.annotation.SqlReposityPlatform;
import cn.bj.zy.core.BaseMapper;
import cn.bj.zy.sbframework.model.platform.TbTeacher;

@SqlReposityPlatform
public interface TbTeacherMapper extends BaseMapper<TbTeacher>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbg.generated
     */
    int insert(TbTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbg.generated
     */
    TbTeacher selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_teacher
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbTeacher record);
}